#!/bin/sh

if [ `dirname $0` != . ]; then
    cd $(dirname $(realpath $0))
fi

port=${1:-5000}
log_dir=${2:-/var/log}

cont=`docker run --rm -d -v $log_dir:/var/log:ro \
    jbieron/tailog:0.1 -h 0.0.0.0 -p $port`

ip=$(docker inspect $cont -f {{.NetworkSettings.IPAddress}})
echo
echo Server will be visible on http://$ip:$port
echo
docker attach $cont
