#!/bin/sh

if [ `dirname $0` != . ]; then
    cd $(dirname $(realpath $0))
fi

set -e

python3 -mvenv venv
. venv/bin/activate
pip3 install -r requirements.txt

echo
echo Installation complete
echo 'Run "source venv/bin/activate" and "flask run [-p PORT]" in '$(pwd)
